language: go
go:
  - '1.11'
env:
  - GOMETALINTER_VER=2.0.11
  - GOMETALINTER_VER=2.0.11 GO111MODULE=on
before_script:
  - pushd $HOME
  - wget https://github.com/alecthomas/gometalinter/releases/download/v${GOMETALINTER_VER}/gometalinter-${GOMETALINTER_VER}-linux-amd64.tar.gz
  - tar -xzvf gometalinter-${GOMETALINTER_VER}-linux-amd64.tar.gz
  - popd
  - PATH=$HOME/gometalinter-${GOMETALINTER_VER}-linux-amd64:$PATH
script:
  - go build -v
  - go test -v -race ./...
  - gometalinter --disable-all --vendor --enable=goimports --enable=gofmt --enable=vet
    --enable=vetshadow --enable=golint --enable=ineffassign --enable=gosimple --enable=unused ./...
